services:
  - type: web
    name: trading-simulado
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: FIREBASE_DATABASE_URL
        value: https://inversion-simulada-default-rtdb.firebaseio.com
      - key: FIREBASE_API_KEY
        value: AIzaSyCTMbDqF_IGkFamez6GSXUwDKVU0igsuxA
      - key: INITIAL_BALANCE
        value: 2000
      - key: SYMBOLS
        value: BTCUSDT,ETHUSDT,1000PEPEUSDT,WIFUSDT,1000BONKUSDT,1000FLOKIUSDT,MOODENGUSDT,PENGUUSDT,MEMEUSDT,BRETTUSDT,TURBOUSDT,1000CHEEMSUSDT,MEWUSDT,DOGEUSDT,1000LUNCUSDT,1000RATSUSDT,COWUSDT,NEIROUSDT,SWARMSUSDT,IOUSDT,ZKUSDT,1000XECUSDT,REZUSDT,ENAUSDT,STRKUSDT,LISTAUSDT,BOMEUSDT,USUALUSDT,1000SHIBUSDT,1000SATSUSDT,AIXBTUSDT,AVAAIUSDT,TRUMPUSDT,PEOPLEUSDT,GOATUSDT,PNUTUSDT,BIOUSDT,POPCATUSDT,MELANIAUSDT,BANUSDT,NOTUSDT,WUSDT,ICPUSDT,NEARUSDT,JTOUSDT,RENDERUSDT,JUPUSDT,OPUSDT,INJUSDT,ARKMUSDT,SEIUSDT,FETUSDT,FILUSDT,ALGOUSDT,AXSUSDT,TIAUSDT,PYTHUSDT,GMXUSDT,DOTUSDT,COMPUSDT,LDOUSDT,IMXUSDT,STGUSDT,BCHUSDT,YGGUSDT,ROSEUSDT,APTUSDT,BNBUSDT,SOLUSDT,CHZUSDT,AVAXUSDT,IOTAUSDT,FIDAUSDT,VTHOUSDT,RLCUSDT,CVCUSDT,POWRUSDT,ZRXUSDT,SANDUSDT,FLOWUSDT,TUSDT,HBARUSDT,ICXUSDT,CTSIUSDT,JOEUSDT,LPTUSDT,ADAUSDT,RAREUSDT,GTCUSDT,AUCTIONUSDT,1INCHUSDT,CKBUSDT,ARBUSDT,WAXPUSDT,ASTRUSDT,STXUSDT,OGNUSDT,MOVRUSDT,GRTUSDT,COTIUSDT,XMRUSDT,TLMUSDT,ANKRUSDT,LTCUSDT,ZILUSDT,MAGICUSDT,TRXUSDT,BATUSDT,CTKUSDT,IOSTUSDT,MTLUSDT,SNXUSDT,WLDUSDT,SUSHIUSDT,KASUSDT,ZROUSDT,AGLDUSDT,DYDXUSDT,ORDIUSDT,ATOMUSDT,ACEUSDT,CELRUSDT,PENDLEUSDT,ETHFIUSDT,CFXUSDT,UMAUSDT,SUPERUSDT,CRVUSDT,XAIUSDT,RUNEUSDT,THETAUSDT,ALTUSDT,STEEMUSDT,MAVUSDT,CYBERUSDT,MAVIAUSDT,BICOUSDT,VETUSDT,KNCUSDT,C98USDT,API3USDT,NFPUSDT,PIXELUSDT,RONINUSDT,POLYXUSDT,ONEUSDT,ACHUSDT,BLURUSDT,MANAUSDT,UNIUSDT,EGLDUSDT,STORJUSDT,AAVEUSDT,TRBUSDT,ALICEUSDT,METISUSDT,SKLUSDT,SUNUSDT,ARPAUSDT,SUIUSDT,ENSUSDT,XRPUSDT
      - key: BINANCE_REST_URL
        value: https://fapi.binance.com
